### Notebook for testing NumPy functions

Python's memory model isn't strictly "pass-by-value" or "pass-by-reference" like it is in C++. It's often called "pass-by-assignment" or "pass-by-object-reference."

Here’s a simple way to think about it:
    
- When you create an object (like a big NumPy array), it lives in a specific place in memory.
    
- The variable you assign it to (e.g., `my_grid`) isn't the object itself; it's just a **label** or a **pointer** that points to the object in memory.

When you pass `my_grid` to a function, Python **does not copy the entire array**. It only copies the small pointer. Inside the function, the parameter is a new label, but it points to the **exact same object** in memory.

In [1]:
import numpy as np

def modify_grid_in_place(grid_data):
    """This function modifies the array it receives."""
    print(f"  Inside function, object ID: {id(grid_data)}")
    # Modify the first element
    grid_data[0, 0] = 99.0

# 1. Create our main grid
my_grid = np.zeros((5, 5))
print(f"Original grid's object ID: {id(my_grid)}")
print("Original grid:\n", my_grid)

# 2. Pass the grid to the function
modify_grid_in_place(my_grid)

# 3. Check the original grid
print("Grid after function call:\n", my_grid)

Original grid's object ID: 4416290032
Original grid:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
  Inside function, object ID: 4416290032
Grid after function call:
 [[99.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


### Mutable vs. Immutable Objects

The key difference in behavior depends on whether the object is **mutable** (can be changed) or **immutable** (cannot be changed).

- **Immutable Objects:** Numbers, strings, and tuples. If you try to "change" one inside a function, Python creates a brand new object. The original is unaffected.
    
- **Mutable Objects:** Lists, dictionaries, and most importantly for you, **NumPy arrays**. These can be changed in-place.
    
Since the simulation grid is a NumPy array (a mutable object), any function that modifies it will be modifying the original object.